application: wepoco-map
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /(.*\.(html|css|js))
  static_files: pages/\1
  upload: pages/(.*\.(html|css|js))

- url: /
  static_files: pages/observations-dev.html
  upload: pages/observations-dev.html

- url: /about
  static_files: pages/about.html
  upload: pages/about.html

- url: /help
  static_files: pages/help.html
  upload: pages/help.html

- url: .*
  script: wepoco-map.py

