application: wepoco-map
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /(.*\.jpg)
  static_files: images/jpegs/\1
  upload: images/jpegs(.*\.jpg)

- url: /(.*\.kml)
  static_files: images/\1
  upload: images/(.*\.kml)

- url: /demo/
  static_files: demo/index.html
  upload: demo/index.html

- url: /demo/(.*)
  static_files: demo/\1
  upload: demo/(.*)

- url: /atlas/(.*)
  static_files: atlas/\1
  upload: atlas/(.*)

- url: /(.*\.(html|css|js|gif))
  static_files: pages/\1
  upload: pages/(.*\.(html|css|js|gif))

- url: /
  static_files: pages/observations.html
  upload: pages/observations.html

- url: /admin
  script: admin.py

- url: /about
  static_files: pages/about.html
  upload: pages/about.html

- url: /help
  static_files: pages/help.html
  upload: pages/help.html

- url: /tile.*
  script: maptile.py     

- url: .*
  script: wepoco-map.py

