application: wepoco-map
version: 1
runtime: python
api_version: 1

builtins:

- datastore_admin: on

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /(.*\.jpg)
  static_files: images/jpegs/\1
  upload: images/jpegs(.*\.jpg)

- url: /(.*\.kml)
  static_files: images/\1
  upload: images/(.*\.kml)

- url: /demo
  static_files: demo/index.html
  upload: demo/index.html

- url: /demo/(.*)
  static_files: demo/\1
  upload: demo/(.*)

- url: /atlas/(.*)
  static_files: atlas/\1
  upload: atlas/(.*)

- url: /datastore
  static_files: admin/datastore.html
  upload: admin/datastore.html
  login: admin

- url: /(.*\.(html|css|js|gif))
  static_files: pages/\1
  upload: pages/(.*\.(html|css|js|gif))

- url: /admin
  script: admin.py
  login: admin

- url: /about
  static_files: pages/about.html
  upload: pages/about.html

- url: /help
  static_files: pages/help.html
  upload: pages/help.html

- url: /
  static_files: pages/index.html
  upload: pages/index.html

- url: /done
  static_files: pages/index.html
  upload: pages/index.html

- url: /list.*
  script: wepoco-map.py
  login: admin

- url: /del.*
  script: wepoco-map.py


- url: /adata
  script: wepoco-map.py

- url: /arfe
  script: wepoco-map.py

- url: /arean
  script: wepoco-map.py

- url: /arfeimg
  script: wepoco-map.py

- url: /andvi
  script: wepoco-map.py

- url: /andviimg
  script: wepoco-map.py

- url: /uploadform
  script: wepoco-map.py

- url: /uploadurl
  script: wepoco-map.py

- url: /upload.*
  script: wepoco-map.py

- url: /picuploadurl
  script: wepoco-map.py

- url: /picupload.*
  script: wepoco-map.py

- url: /serve/.*
  script: wepoco-map.py
 



